require("__corrundum__.prototypes.particles")
require("__corrundum__.prototypes.entities")
require("__corrundum__.prototypes.factoriopedia-simulations")
require("__corrundum__.prototypes.fluid")
require("__corrundum__.prototypes.item")

require("__corrundum__.prototypes.recipe-category")
require("__corrundum__.prototypes.recipe")
require("__corrundum__.prototypes.remnants")
require("__corrundum__.prototypes.technology")
require("__corrundum__.prototypes.item-groups")

require("__corrundum__.prototypes.entity.resources")
require("__corrundum__.prototypes.planet.corrundum-map-gen")
require("__corrundum__.prototypes.planet.planet")
require("__corrundum__.prototypes.planet.procession-catalogue-corrundum")
require("__corrundum__.prototypes.tile.tiles-corrundum")
require("__corrundum__.prototypes.autoplace-controls")
require("__corrundum__.prototypes.planet.corrundum-expressions")
require("__corrundum__.prototypes.corrundum-decoratives")
require("__corrundum__.prototypes.ambient-sounds")
require("__corrundum__.prototypes.achievements")

require("__corrundum__.compatibility.canal-excavator")